### ISSUE TITLE
RIPT - New row key adds more than one row

### ISSUE THREAD

**Issue by daniviga** [gem/oq-platform#503] opened 2015-11-04 10:18 UTC
In the Risk Preparation Tool after playing with the drop down menus, when you try to add a new row (with `ctrl-shift-n`) more than one row is added (equal to the number of fields changed). It looks like more a bug in the library: the `.destroy()` method (fired when a menu option is changed: https://github.com/gem/oq-platform/blob/risk-ipt-bug3/openquakeplatform/openquakeplatform/static/js/risk_input_model_exposure.js#L121) is not completely removing the table from the DOM, so the `.keyup` listener iterates on N tables (https://github.com/gem/oq-platform/blob/risk-ipt-bug3/openquakeplatform/openquakeplatform/static/js/risk_input_model_exposure.js#L204).

**Comment by nastasi-oq** [comment] 2016-02-22 14:19
The problem is clear (callbacks added multiple times to a filter-by-class) when all the code will be reviewed the bug will be closed.
Already solved in Exposure and Fragility tab.

**Comment by nastasi-oq** [comment] 2016-03-15 09:00
Fixed in d1669f9b5a82366884560e60cac3b051fcd826c9 (risk-ipt-new-vuln-tables branch, ript-refact01 milestone).

**Closed** 2016-03-24 08:53 UTC
Labels: Committed
