### ISSUE TITLE
In layers and maps zoom stops to work after first modification

### ISSUE THREAD

**Issue by nastasi-oq** [gem/oq-platform#484] opened 2015-10-14 09:22 UTC
Even if you use mouse wheel or "+"/"-" buttons zoom stops to update the map and the zoom cursor.

**Comment by daniviga** [comment] 2015-10-14 09:29
It looks like that something has changed in the browsers: this feature I'm sure it was working before, but now it seems that also other GeoNode 2.0 installation are broken. See for example:
- http://charim-geonode.net/layers/geonode:vct_adm1
- http://yolandadata.org/layers/geonode:noah_leyte_taclobancity_flood_100year

**Comment by daniviga** [comment] 2015-10-14 09:31
The GeoNode 2.4 demo (with an up-to-date GeoExplorer) works:
- http://demo.geonode.org/maps/34

**Comment by pslh** [comment] 2015-10-14 10:11
Bug confirmed on:
Ubuntu 14.04 Chromium+Firefox, 
Ubuntu 12.04 Chromium+Firefox, 
Safari 9.0 on Mac OS X 10.9.5.

**Comment by pslh** [comment] 2015-10-14 10:24
Bug also confirmed on Ubuntu 10.10 Chrome+Firefox.  I have certainly not updated this software in the last year.

**Comment by pslh** [comment] 2015-10-14 11:48
Appears to be this Bing related issue:
https://github.com/GeoNode/geonode/issues/2303

**Comment by daniviga** [comment] 2015-10-14 15:49
The issue has been resolved with a manual migration; see http://lists.osgeo.org/pipermail/geonode-devel/2015-October/000498.html for more details. We still need to address the development workflow.

**Closed by daniviga** 2015-10-14 15:49 UTC
Labels: Hotfix
